In [151]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import RandomOverSampler
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras import Input
from keras.layers import Dense, Flatten,Dropout
import pandas as pd 
import numpy as np 
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import plotly 
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import accuracy_score
from prettytable import PrettyTable
from sklearn.neural_network import MLPClassifier
from sklearn.decomposition import PCA

In [152]:
def model_predict(test_var):
    ans_ds = model_ds.predict(test_var)
    ans_cc = model_cc.predict(test_var)
    ans_cy = model_cy.predict(test_var)
    ans_core = model_core.predict(test_var)
    results = np.concatenate((ans_cc,ans_core,ans_cy,ans_ds),axis = 1)
    results_ans = []
    for i in results:
        x = list(i)
        results_ans+= [x.index(max(x))]
    return results_ans 

In [153]:
#from sklearn.decomposition import PCA
#pca = PCA(n_components=20)
le = LabelEncoder()
oversample = RandomOverSampler()
df = pd.read_csv('final_datasets/encoded_dataset.csv') #dataset
#pca = PCA(n_components=20)
#pca_values = pca.fit(df.iloc[:,3:]).singular_values_
#df = pd.read_csv("data/proper_dataset.csv")
X = df.iloc[:,2:]
y = le.fit_transform(df['Streams'])
X, y= oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_test=np.asarray(X_test.iloc[:,1:]).astype(np.int)
#y_test=tensorflow.one_hot(np.asarray(y_test).astype(np.int),depth=4)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14428\1396530780.py:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_test=np.asarray(X_test.iloc[:,1:]).astype(np.int)


In [154]:
input_neuron = 1091
hidden_neuron1 =512
hidden_neuron2 = 512
hidden_neuron3 = 512
hidden_neuron4 = 512
active_hidden = "softplus"
active = "sigmoid"

In [155]:
X_train_cc = np.asarray(X_train.loc[X_train['Streams']=='cloud computing'].iloc[:,1:]).astype(np.int)
X_train_cy = np.asarray(X_train.loc[X_train['Streams']=='cyber security'].iloc[:,1:]).astype(np.int)
X_train_core = np.asarray(X_train.loc[X_train['Streams']=='data science'].iloc[:,1:]).astype(np.int)
X_train_ds = np.asarray(X_train.loc[X_train['Streams']=='data science'].iloc[:,1:]).astype(np.int)


X_train_cc_new = np.concatenate((X_train_cc,X_train_ds[:X_train_cc.shape[0]//5]))
X_train_core_new = np.concatenate((X_train_core,X_train_ds[:X_train_core.shape[0]//5]))
X_train_cy_new = np.concatenate((X_train_cy,X_train_ds[:X_train_cy.shape[0]//5]))
X_train_ds_new = np.concatenate((X_train_ds,X_train_cc[:X_train_cc.shape[0]//5]))


y_train_cc = np.concatenate((np.ones(X_train_cc.shape[0]),np.zeros(X_train_cc_new.shape[0]-X_train_cc.shape[0])))
y_train_core = np.concatenate((np.ones(X_train_core.shape[0]),np.zeros(X_train_core_new.shape[0]-X_train_core.shape[0])))
y_train_cy = np.concatenate((np.ones(X_train_cy.shape[0]),np.zeros(X_train_cy_new.shape[0]-X_train_cy.shape[0])))
y_train_ds = np.concatenate((np.ones(X_train_ds.shape[0]),np.zeros(X_train_ds_new.shape[0]-X_train_ds.shape[0])))

y_train_cc = y_train_cc.reshape(y_train_cc.shape[0],1)
y_train_cy = y_train_cy.reshape(y_train_cy.shape[0],1)
y_train_core = y_train_core.reshape(y_train_core.shape[0],1)
y_train_ds = y_train_ds.reshape(y_train_ds.shape[0],1)


#X_train_ds = np.asarray(X_train.loc[X_train['Streams']=='data science'].iloc[:,1:]).astype(np.int)

#X_train_cc = (pca.fit(X_train_cc)).singular_values_
#X_train_core = (pca.fit(X_train_core)).singular_values_
#X_train_cy = (pca.fit(X_train_cy)).singular_values_
#X_train_ds = (pca.fit(X_train_ds)).singular_values_
    
#y_train_cc = np.array([1 if i == 0 else 0 for i in y_train])
#y_train_core = np.array([1 if i == 1 else 0 for i in y_train])
#y_train_cy = np.array([1 if i == 2 else 0 for i in y_train])
#y_train_ds = np.array([1 if i == 3 else 0 for i in y_train])


#y_train_cc = np.broadcast_to(np.array([1]), (X_train_cc.shape[0], 1))
#y_train_core = np.broadcast_to(np.array([1]), (X_train_core.shape[0], 1))
#y_train_cy = np.broadcast_to(np.array([1]), (X_train_cy.shape[0], 1))
#y_train_ds = np.broadcast_to(np.array([1]), (X_train_ds.shape[0], 1))

y_test_cc = np.array([[1] if i == 0 else [0] for i in y_test])
y_test_core = np.array([[1] if i == 1 else [0] for i in y_test])
y_test_cy = np.array([[1] if i == 2 else [0] for i in y_test])
y_test_ds = np.array([[1] if i == 3  else [0] for i in y_test])


C:\Users\ASUS\AppData\Local\Temp\ipykernel_14428\1262197013.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train_cc = np.asarray(X_train.loc[X_train['Streams']=='cloud computing'].iloc[:,1:]).astype(np.int)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14428\1262197013.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision

In [148]:
model_cc = Sequential(name="ANN-for-resume-classification-cc")   
model_cc.add(Input(shape=(input_neuron,), name='Input-Layer'))
#model_cc.add(Dropout(.5, input_shape=(input_neuron,)))
model_cc.add(Dense(hidden_neuron1, activation=active_hidden, name='Hidden-Layer'))
#model_cc.add(Dense(64, activation='softplus', name='Hidden-Layer-2'))
#model_cc.add(Dense(8, activation='softplus', name='Hidden-Layer-3'))
model_cc.add(Dense(1, activation=active, name='Output-Layer'))


model_cc.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['Accuracy', 'Precision', 'Recall'],
              loss_weights=None,
              weighted_metrics=None,
              run_eagerly=None,
              steps_per_execution=None
              )

model_cc.fit(X_train_cc_new,
          y_train_cc,
          batch_size=10,
          epochs=200,
          verbose='auto',
         )


model_core = Sequential(name="ANN-for-resume-classification-core")
model_core.add(Input(shape=(input_neuron,), name='Input-Layer'))
#model_core.add(Dropout(.1, input_shape=(input_neuron,)))
model_core.add(Dense(hidden_neuron2, activation=active_hidden, name='Hidden-Layer'))
#model_core.add(Dense(64, activation='softplus', name='Hidden-Layer-2'))
#model_core.add(Dense(8, activation='softplus', name='Hidden-Layer-3'))
model_core.add(Dense(1, activation=active, name='Output-Layer'))


model_core.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['Accuracy', 'Precision', 'Recall'],
              loss_weights=None,
              weighted_metrics=None,
              run_eagerly=None,
              steps_per_execution=None
              )

model_core.fit(X_train_core_new,
          y_train_core,
          batch_size=10,
          epochs=200,
          verbose='auto',
         )

model_cy = Sequential(name="ANN-for-resume-classification-cy")
model_cy.add(Input(shape=(input_neuron,), name='Input-Layer'))
#model_cy.add(Dropout(.5, input_shape=(input_neuron,)))
model_cy.add(Dense(hidden_neuron3, activation=active_hidden, name='Hidden-Layer'))
#model_cy.add(Dense(64, activation='softplus', name='Hidden-Layer-2'))
#model_cy.add(Dense(8, activation='softplus', name='Hidden-Layer-3'))
model_cy.add(Dense(1, activation=active, name='Output-Layer'))


model_cy.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['Accuracy', 'Precision', 'Recall'],
              loss_weights=None,
              weighted_metrics=None,
              run_eagerly=None,
              steps_per_execution=None
              )

model_cy.fit(X_train_cy_new,
          y_train_cy,
          batch_size=10,
          epochs=200,
          verbose='auto',
         )

model_ds = Sequential(name="ANN-for-resume-classification-ds")
model_ds.add(Input(shape=(input_neuron,), name='Input-Layer'))

#model_ds.add(Dropout(.2, input_shape=(input_neuron,)))
model_ds.add(Dense(hidden_neuron4, activation=active_hidden, name='Hidden-Layer'))
#model_ds.add(Dense(64, activation='softplus', name='Hidden-Layer-2'))
#model_ds.add(Dense(8, activation='softplus', name='Hidden-Layer-3'))
model_ds.add(Dense(1, activation=active, name='Output-Layer'))


model_ds.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['Accuracy', 'Precision', 'Recall'],
              loss_weights=None,
              weighted_metrics=None,
              run_eagerly=None,
              steps_per_execution=None
              )

model_ds.fit(X_train_ds_new,
          y_train_ds,
          batch_size=10,
          epochs=200,
          verbose='auto',
         )
         

Epoch 1/100
16/16 [==============================] - 1s 5ms/step - loss: 0.4144 - Accuracy: 0.8333 - precision: 0.8333 - recall: 1.0000
Epoch 2/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2337 - Accuracy: 0.8654 - precision: 0.8609 - recall: 1.0000
Epoch 3/100
16/16 [==============================] - 0s 5ms/step - loss: 0.1525 - Accuracy: 0.9808 - precision: 0.9774 - recall: 1.0000
Epoch 4/100
16/16 [==============================] - 0s 6ms/step - loss: 0.1079 - Accuracy: 0.9679 - precision: 0.9630 - recall: 1.0000
Epoch 5/100
16/16 [==============================] - 0s 6ms/step - loss: 0.0763 - Accuracy: 0.9936 - precision: 0.9924 - recall: 1.0000
Epoch 6/100
16/16 [==============================] - 0s 6ms/step - loss: 0.0544 - Accuracy: 0.9936 - precision: 0.9924 - recall: 1.0000
Epoch 7/100
16/16 [==============================] - 0s 6ms/step - loss: 0.0419 - Accuracy: 0.9936 - precision: 0.9924 - recall: 1.0000
Epoch 8/100
16/16 [=============================

16/16 [==============================] - 0s 5ms/step - loss: 5.6774e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 61/100
16/16 [==============================] - 0s 5ms/step - loss: 5.4371e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 62/100
16/16 [==============================] - 0s 5ms/step - loss: 5.2415e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 63/100
16/16 [==============================] - 0s 4ms/step - loss: 5.0553e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 64/100
16/16 [==============================] - 0s 5ms/step - loss: 4.8912e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 65/100
16/16 [==============================] - 0s 5ms/step - loss: 4.7101e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 66/100
16/16 [==============================] - 0s 5ms/step - loss: 4.5533e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 67/100
16/16 [======

16/16 [==============================] - 0s 5ms/step - loss: 0.2581 - Accuracy: 0.8250 - precision: 0.8354 - recall: 0.9851
Epoch 19/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2562 - Accuracy: 0.7688 - precision: 0.8345 - recall: 0.9030
Epoch 20/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2543 - Accuracy: 0.7625 - precision: 0.8429 - recall: 0.8806
Epoch 21/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2472 - Accuracy: 0.7875 - precision: 0.8676 - recall: 0.8806
Epoch 22/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2557 - Accuracy: 0.8062 - precision: 0.8552 - recall: 0.9254
Epoch 23/100
16/16 [==============================] - 0s 4ms/step - loss: 0.2697 - Accuracy: 0.7812 - precision: 0.8898 - recall: 0.8433
Epoch 24/100
16/16 [==============================] - 0s 4ms/step - loss: 0.2590 - Accuracy: 0.8125 - precision: 0.8562 - recall: 0.9328
Epoch 25/100
16/16 [==============================] - 

16/16 [==============================] - 0s 5ms/step - loss: 0.2494 - Accuracy: 0.8062 - precision: 0.8456 - recall: 0.9403
Epoch 78/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2508 - Accuracy: 0.7750 - precision: 0.8267 - recall: 0.9254
Epoch 79/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2503 - Accuracy: 0.8125 - precision: 0.9561 - recall: 0.8134
Epoch 80/100
16/16 [==============================] - 0s 4ms/step - loss: 0.2467 - Accuracy: 0.7937 - precision: 0.8531 - recall: 0.9104
Epoch 81/100
16/16 [==============================] - 0s 4ms/step - loss: 0.2516 - Accuracy: 0.7937 - precision: 0.8686 - recall: 0.8881
Epoch 82/100
16/16 [==============================] - 0s 4ms/step - loss: 0.2523 - Accuracy: 0.8313 - precision: 0.9908 - recall: 0.8060
Epoch 83/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2534 - Accuracy: 0.8250 - precision: 0.8354 - recall: 0.9851
Epoch 84/100
16/16 [==============================] - 

16/16 [==============================] - 0s 5ms/step - loss: 0.0026 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 37/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0024 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 38/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0023 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 39/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0022 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 40/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0021 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 41/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0019 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 42/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0018 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 43/100
16/16 [==============================] - 

16/16 [==============================] - 0s 5ms/step - loss: 2.9566e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 95/100
16/16 [==============================] - 0s 5ms/step - loss: 2.8695e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 96/100
16/16 [==============================] - 0s 5ms/step - loss: 2.7980e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 97/100
16/16 [==============================] - 0s 5ms/step - loss: 2.7353e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 98/100
16/16 [==============================] - 0s 5ms/step - loss: 2.6661e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 99/100
16/16 [==============================] - 0s 5ms/step - loss: 2.5962e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 100/100
16/16 [==============================] - 0s 4ms/step - loss: 2.5345e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 1/100
16/16 [======

16/16 [==============================] - 0s 5ms/step - loss: 0.0012 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 54/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0011 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 55/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0011 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 56/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0011 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 57/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0010 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 58/100
16/16 [==============================] - 0s 4ms/step - loss: 9.7976e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 59/100
16/16 [==============================] - 0s 5ms/step - loss: 9.4279e-04 - Accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000
Epoch 60/100
16/16 [==========================

In [149]:
ans_ds = model_ds.predict(X_test)
ans_cc = model_cc.predict(X_test)
ans_cy = model_cy.predict(X_test)
ans_core = model_core.predict(X_test)
ans = []
for x in y_test:
    if x == 0:
        ans.append("cloud computing")
    if x == 1:
        ans.append("core")
    if x == 2:
        ans.append("cyber security")
    if x == 3:
        ans.append("data science")
table = PrettyTable()
table.add_column("cc", ans_cc)
table.add_column("core", ans_core)
table.add_column("cy", ans_cy)
table.add_column("ds", ans_ds)
table.add_column("ans", ans)
print(table)
ans = []
for x in y_test:
    ans.append(x)
    #if x == [1,0,0,0]:
    #    ans.append(0)
    #if x == [0,1,0,0]:
    #    ans.append(1)
    #if x == [0,0,1,0]:
    #    ans.append(2)
    #if x == [0,0,0,1]:
    #    ans.append(3)

y_pred = model_predict(X_test)
score = accuracy_score(ans, y_pred,normalize = True)


5/5 [==============================] - 0s 3ms/step
+--------------+--------------+--------------+----------------+-----------------+
|      cc      |     core     |      cy      |       ds       |       ans       |
+--------------+--------------+--------------+----------------+-----------------+
| [0.8213074]  | [0.9816336]  | [0.37626913] |  [0.9783252]   |       core      |
| [0.99998295] |  [0.999965]  | [0.9963078]  |  [0.76770306]  | cloud computing |
| [0.40991855] | [0.97375727] | [0.19207615] |  [0.99570215]  |       core      |
| [0.8058762]  | [0.95100063] | [0.99969876] |  [0.9914314]   |  cyber security |
| [0.99998754] | [0.99950874] | [0.89927834] |  [0.78906626]  | cloud computing |
| [0.93411404] | [0.99693066] | [0.8379079]  |  [0.92124707]  |       core      |
| [0.99992347] | [0.99997187] | [0.9975984]  |  [0.99789953]  |   data science  |
| [0.9099098]  | [0.99549747] | [0.87840354] |  [0.99828345]  |       core      |
| [0.9818854]  | [0.99165136] | [0.92550975] | 

5/5 [==============================] - 0s 4ms/step


In [150]:
print(score)

0.6230769230769231


In [46]:
X_train_cc = np.asarray(X_train.loc[X_train['Streams']=='cloud computing'].iloc[:,1:]).astype(np.int)
X_train_cy = np.asarray(X_train.loc[X_train['Streams']=='cyber security'].iloc[:,1:]).astype(np.int)
X_train_core = np.asarray(X_train.loc[X_train['Streams']=="core"].iloc[:,1:]).astype(np.int)
X_train_ds = np.asarray(X_train.loc[X_train['Streams']=='data science'].iloc[:,1:]).astype(np.int)


C:\Users\ASUS\AppData\Local\Temp\ipykernel_14428\712259025.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train_cc = np.asarray(X_train.loc[X_train['Streams']=='cloud computing'].iloc[:,1:]).astype(np.int)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_14428\712259025.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. 

In [47]:
X_train_cc.shape

(44, 1091)

In [48]:
X_train_ds.shape

(127, 1091)

In [49]:
X_train_core.shape

(106, 1091)

In [50]:
X_train_cy.shape

(43, 1091)

In [75]:
rand = np.array([1,2,3,4,5])
rand.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [126]:
from sklearn.svm import OneClassSVM
clf_cc = OneClassSVM(gamma='auto').fit(X_train_cc)
clf_cc.predict(X_test)

array([-1,  1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1,
        1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1, -1,  1,
       -1,  1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1,  1, -1, -1,  1, -1,
       -1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,
       -1, -1, -1,  1, -1,  1, -1, -1, -1,  1, -1,  1], dtype=int64)

In [127]:
clf_core = OneClassSVM(gamma='auto').fit(X_train_core)
clf_core.predict(X_test)

array([-1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,
        1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,
       -1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1,
        1,  1,  1, -1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1,
       -1, -1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1], dtype=int64)

In [128]:
clf_cy = OneClassSVM(gamma='auto').fit(X_train_cy)
clf_cy.predict(X_test)

array([-1,  1,  1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1,  1,  1,
        1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,
       -1,  1,  1, -1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1,
        1,  1,  1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1, -1,  1,  1, -1,
        1, -1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1], dtype=int64)

In [129]:
clf_ds = OneClassSVM(gamma='auto').fit(X_train_ds)
clf_ds.predict(X_test)

array([-1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,
        1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,
       -1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1,
        1,  1,  1, -1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1,
       -1, -1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1], dtype=int64)

In [130]:
y_test

array([0, 1, 3, 1, 1, 3, 1, 1, 2, 2, 1, 3, 0, 2, 3, 0, 2, 1, 1, 3, 1, 3,
       3, 2, 1, 3, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 0,
       3, 0, 2, 2, 2, 3, 1, 3, 3, 0, 2, 3, 3, 0, 1, 3, 3, 0, 1, 3, 3, 2,
       1, 0, 2, 3, 3, 1, 2, 1, 3, 2, 3, 1, 1, 3])

In [ ]:
y_pred = 